---
# See https://github.com/jvautier/project-cli
fullname: jvautier/ansible-role-gpg
description: Install gpg utilities through ansible
tags:
  - ansible
  - ansible-role
  - gpg
github:
  has_issues: true
  has_projects: false
  has_wiki: false
